In [30]:
import pandas as pd

df_housing = pd.read_csv("/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/data/seoul_real_estate_en.csv")
df_bdong = pd.read_csv("/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/data/bdong_eng.txt", 
                        sep="|", header=None, names=["CODE", "STDG_NM_KR", "STDG_NM_EN"], encoding="cp949")


df_housing['CODE'] = df_housing['CGG_CD'].astype(str) + df_housing['STDG_CD'].astype(str)
df_bdong['CODE'] = df_bdong['CODE'].astype(str)

df_housing = df_housing.merge(df_bdong[['CODE', 'STDG_NM_EN']], on='CODE', how='left')
df_housing['STDG_NM'] = df_housing['STDG_NM_EN']
df_housing.drop(columns=['STDG_NM_EN'], inplace=True)
display(df_housing[['CGG_CD', 'CGG_NM', 'STDG_NM']].head(10))

output_path = "/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/data/seoul_housing_en_updated.csv"
df_housing.to_csv(output_path, index=False, encoding="utf-8")

   CGG_CD CGG_NM         STDG_NM
0   11230   동대문구   Dapsipni-dong
1   11650    서초구     Jamwon-dong
2   11530    구로구   Garibong-dong
3   11500    강서구   Oebalsan-dong
4   11620    관악구  Bongcheon-dong
5   11740    강동구    Cheonho-dong
6   11305    강북구       Suyu-dong
7   11740    강동구    Cheonho-dong
8   11215    광진구       Guui-dong
9   11380    은평구   Yeokchon-dong

In [32]:
import json

file_path = '/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/in_en.json'
df_housing = pd.read_csv("/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/data/seoul_housing_en_updated.csv")

with open(file_path, 'r', encoding='utf-8') as file:
    mappings = json.load(file)

# Step 2: Access the dictionaries for BLDG_USG and CGG_NM mappings
cgn_nm_mapping = mappings['cgn_nm_mapping']
lotno_se_nm_mapping = mappings['lotno_se_nm_mapping']
rght_se_mapping = mappings['rght_se_mapping']
bldg_usg_mapping = mappings['bldg_usg_mapping']
dclr_se_mapping = mappings['dclr_se_mapping']

df_housing['CGG_NM'] = df_housing['CGG_NM'].replace(cgn_nm_mapping)
df_housing['LOTNO_SE_NM'] = df_housing['LOTNO_SE_NM'].replace(lotno_se_nm_mapping)
df_housing['RGHT_SE'] = df_housing['RGHT_SE'].replace(rght_se_mapping)
df_housing['BLDG_USG'] = df_housing['BLDG_USG'].replace(bldg_usg_mapping)
df_housing['DCLR_SE'] = df_housing['DCLR_SE'].replace(dclr_se_mapping)

df_housing[['CGG_CD', 'CGG_NM', 'LOTNO_SE_NM', 'RGHT_SE', 'STDG_NM', 'BLDG_USG']].head()
df_housing.to_csv(output_path, index=False, encoding="utf-8")

In [ ]:
from googletrans import Translator
from tqdm import tqdm
import pandas as pd

translator = Translator()

def translate_building_name(name):
    try:
        return translator.translate(name, src='ko', dest='en').text
    except Exception as e:
        return name
        
tqdm.pandas()

df_housing['BLDG_NM_EN'] = df_housing['BLDG_NM'].progress_apply(translate_building_name)
df_housing.to_csv(output_path, index=False, encoding="utf-8")

display(df_housing[['BLDG_NM', 'BLDG_NM_EN']])

In [34]:
df_housing = pd.read_csv("/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/data/seoul_housing_en_updated.csv")
df_housing[['BLDG_NM', 'BLDG_NM_EN']]

            BLDG_NM                           BLDG_NM_EN
0           현대썬앤빌청계        Hyundai Sun & Ville Cheonggye
1             멀버리힐스                       Mulberry Hills
2         삼부르네상스파크빌        Sambura Renaissance Parkville
3               가온빌                            Gaon Bill
4            백조아트빌라                       Swan Art Villa
...             ...                                  ...
22995  연신내역트리플라101동       Yeondin History Triple Pla 101
22996  역삼역센트럴푸르지오시티  Yeoksam Station Central Prugio City
22997     엘에이치서초4단지                 L H Seocho 4 Complex
22998            엘림                                 Elim
22999      엘리젠트오피스텔                     Elized Officetel

[23000 rows x 2 columns]

In [47]:
def needs_translation(text):
    return pd.isna(text) or all('\uac00' <= char <= '\ud7a3' for char in str(text))  # 한글만 포함된 경우

mask = df_housing['BLDG_NM_EN'].apply(needs_translation)
df_housing.loc[mask, 'BLDG_NM_EN'] = df_housing.loc[mask, 'BLDG_NM'].progress_apply(translate_building_name)

df_housing.to_csv(output_path, index=False, encoding="utf-8")

display(df_housing[['BLDG_NM', 'BLDG_NM_EN']])

100%|██████████| 296/296 [01:32<00:00,  3.21it/s]

            BLDG_NM                           BLDG_NM_EN
0           현대썬앤빌청계        Hyundai Sun & Ville Cheonggye
1             멀버리힐스                       Mulberry Hills
2         삼부르네상스파크빌        Sambura Renaissance Parkville
3               가온빌                            Gaon Bill
4            백조아트빌라                       Swan Art Villa
...             ...                                  ...
22995  연신내역트리플라101동       Yeondin History Triple Pla 101
22996  역삼역센트럴푸르지오시티  Yeoksam Station Central Prugio City
22997     엘에이치서초4단지                 L H Seocho 4 Complex
22998            엘림                                 Elim
22999      엘리젠트오피스텔                     Elized Officetel

[23000 rows x 2 columns]

In [51]:
mask = df_housing['BLDG_NM_EN'].apply(needs_translation)
df_housing.loc[mask, 'BLDG_NM_EN'] = df_housing.loc[mask, 'BLDG_NM'].progress_apply(translate_building_name)

df_housing.to_csv(output_path, index=False, encoding="utf-8")

display(df_housing[['BLDG_NM', 'BLDG_NM_EN']])

100%|██████████| 16/16 [00:04<00:00,  3.56it/s]

            BLDG_NM                           BLDG_NM_EN
0           현대썬앤빌청계        Hyundai Sun & Ville Cheonggye
1             멀버리힐스                       Mulberry Hills
2         삼부르네상스파크빌        Sambura Renaissance Parkville
3               가온빌                            Gaon Bill
4            백조아트빌라                       Swan Art Villa
...             ...                                  ...
22995  연신내역트리플라101동       Yeondin History Triple Pla 101
22996  역삼역센트럴푸르지오시티  Yeoksam Station Central Prugio City
22997     엘에이치서초4단지                 L H Seocho 4 Complex
22998            엘림                                 Elim
22999      엘리젠트오피스텔                     Elized Officetel

[23000 rows x 2 columns]

In [61]:
output_path = "/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/data/seoul_real_estate_en.csv"
df_housing = pd.read_csv("/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/data/seoul_housing_en_updated.csv")
df_cgg_nm = pd.read_csv("/Users/songsooyeoun/Desktop/git_test/streamlit/seoul_housing/data/seoul_real_estate.csv")

df_housing.drop(columns='BLDG_NM', inplace=True)
df_housing.rename(columns={'CGG_NM': 'CGG_NM_EN', 'BLDG_NM_EN':'BLDG_NM'}, inplace=True)
df_housing['CGG_NM'] = df_cgg_nm['CGG_NM']

display(df_housing[['CGG_CD', 'CGG_NM', 'CGG_NM_EN', 'STDG_NM', 'BLDG_NM', 'BLDG_USG']].sample(10))
df_housing.to_csv(output_path, index=False, encoding="utf-8")

,CGG_CD,CGG_NM,CGG_NM_EN,STDG_NM,BLDG_NM,BLDG_USG
20783,11215,광진구,Gwangjin-gu,Jayang-dong,Hangaram Village,Multiplex House
11702,11470,양천구,Yangcheon-gu,Sinjeong-dong,Mokdong Woo Castle 3,Apartment
22949,11290,성북구,Seongbuk-gu,Jeongneung-dong,Jeongneung Hill State 1st,Apartment
1162,11200,성동구,Seongdong-gu,Hawangsimni-dong,Centras,Apartment
14532,11440,마포구,Mapo-gu,Ahyeon-dong,Maporamian Prugio 4 Complex,Apartment
22707,11620,관악구,Gwanak-gu,Bongcheon-dong,Leaders Officetel,Officetel
12354,11410,서대문구,Seodaemun-gu,Daehyeon-dong,Shinchon Lucky,Apartment
14988,11350,노원구,Nowon-gu,Gongneung-dong,Dongbu Apartment,Apartment
19297,11740,강동구,Gangdong-gu,Dunchon-dong,Jeongseong Housing A -dong,Multiplex House
16283,11290,성북구,Seongbuk-gu,Jongam-dong,River Gardenville,Multiplex House